### ISSUE TITLE
Use snake case for all test method names

### ISSUE THREAD

**Issue by slashmo** [slashmo/swift-w3c-trace-context#10]
The project currently uses a mixture of `snake_case` and `lowerCamelCase` for its test methods. We should consolidate this by using `snake_case` everywhere.

**Comment by ktoso** [comment]
That’s not actually the style I use :) it’s a “test_subject_shouldDoWhat_additionalInfo” grouping — if that’s what you want to adopt. 

Otherwise many projects just use camel case... full snake is not really a thing I guess

**Comment by slashmo** [comment]
> That’s not actually the style I use :) it’s a “test_subject_shouldDoWhat_additionalInfo” grouping — if that’s what you want to adopt.
> @ktoso 

This sounds like a good approach 👍

I tried adopting it in #11 and the results are pretty nice 👀
