### ISSUE TITLE
Add convenience API for creating empty TraceState

### ISSUE THREAD

**Issue by slashmo** [slashmo/swift-w3c-trace-context#5]
Currently, the only way to initialize an empty `TraceState` is using the `rawValue` initializer with an empty String:

```swift
let emptyTraceState = TraceState(rawValue: "")!
```

We should get rid of that force-unwrap by adding a more convenient API to create an empty `TraceState`. This might be implemented as a static method on `TraceState`, similar to `TraceParent.random()`:

```swift
public static func none() -> TraceState {
    self._storage = []
}
```

**Comment by ktoso** [comment]
Would : 

```
public static var empty: TraceState
```

read nicer?

**Comment by slashmo** [comment]
> Would :
> 
> ```
> public static var empty: TraceState
> ```
> 
> read nicer?
> @ktoso 

Yeah, `.empty` also reads nicely 👍 It will probably be used sometimes in conjunction with `TraceParent.random()` like this:

```swift
let traceContext = TraceContext(parent: .random(), state: .empty)
let traceContext = TraceContext(parent: .random(), state: .none())
```

Not sure which option I prefer in this case. I think regardless of the name having a computed property instead of a method makes sense in this case as we don't need an overload of it that takes some argument.

One other option I thought about was to create an initializer without arguments, but I found that to be not specific enough. What do you think?

**Comment by slashmo** [comment]
The advantage of `.empty` over `.none` is that it doesn't look like the `nil` case of an `Optional`, so I'd prefer `.empty`.

**Comment by ktoso** [comment]
Oh i see... "state: .none" actually reads better in "normal english" so that could be good 👍 

 // but as a var, no need for func

**Comment by slashmo** [comment]
Readability wins 👉 `TraceState.none` it is 😊
